"""Generate EXPERIMENT_REPORT.md from all campaign results.

Cross-campaign synthesis entry point for Phase 8.  Loads all available
campaign directories, calls the analysis functions from generate_tables.py,
and writes a comprehensive markdown report.

Usage:
    cd BackEnd && python scripts/generate_report.py
    cd BackEnd && python scripts/generate_report.py --results-dir results/campaigns --output-dir results/figures
"""
import argparse
import json
import logging
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from scripts.generate_tables import (
    generate_all_outputs,
    generate_ablation_table_with_pvalues,
    generate_combined_extensions_table,
    load_campaign_results,
    plot_combined_comparison,
    plot_convergence_curves,
    plot_per_topology,
    results_to_dataframe,
    select_best_config_name,
    wilcoxon_compare,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Report generator
# ---------------------------------------------------------------------------

def generate_experiment_report(
    campaign_dirs: dict,
    figures_dir: str,
    output_path: str,
) -> None:
    """Generate EXPERIMENT_REPORT.md from available campaign directories.

    Args:
        campaign_dirs: Mapping of campaign key to directory path.
            Expected keys: "baseline", "fedprox", "cooperative", "tod"
            (any subset is valid — missing dirs produce "not available" notes).
        figures_dir: Directory where figures and tables will be written.
        output_path: File path for the output EXPERIMENT_REPORT.md.
    """
    os.makedirs(figures_dir, exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    lines = []

    # ------------------------------------------------------------------
    # 1. Header
    # ------------------------------------------------------------------
    lines += [
        "# SEAL Experiment Report",
        "",
        "*Auto-generated by generate_report.py*",
        "",
    ]

    # ------------------------------------------------------------------
    # Load available campaign results
    # ------------------------------------------------------------------
    loaded: dict = {}
    for key, path in campaign_dirs.items():
        results_path = os.path.join(path, "results.json")
        if os.path.exists(results_path):
            try:
                loaded[key] = load_campaign_results(path)
                logger.info("Loaded campaign %r from %s (%d results)", key, path, len(loaded[key]))
            except Exception as exc:
                logger.warning("Failed to load campaign %r: %s", key, exc)
        else:
            logger.info("Campaign %r directory missing or has no results.json: %s", key, path)

    baseline_results = loaded.get("baseline", [])

    # ------------------------------------------------------------------
    # 2. Key Findings
    # ------------------------------------------------------------------
    lines += [
        "## Key Findings",
        "",
    ]

    if baseline_results:
        baseline_df = results_to_dataframe(baseline_results)
        fedrl_rows = baseline_df[baseline_df["trainer"] == "FedRL"]
        if not fedrl_rows.empty:
            baseline_mean = fedrl_rows.iloc[0]["avg_waiting_time_mean"]
            baseline_name = fedrl_rows.iloc[0]["name"]
        elif not baseline_df.empty:
            baseline_mean = baseline_df.iloc[0]["avg_waiting_time_mean"]
            baseline_name = baseline_df.iloc[0]["name"]
        else:
            baseline_mean = None
            baseline_name = "baseline"

        ablation_keys = {
            "fedprox": "FedProx ablation",
            "cooperative": "Cooperative reward ablation",
            "tod": "Time-of-day ablation",
        }

        for key, label in ablation_keys.items():
            if key in loaded and loaded[key]:
                best_name = select_best_config_name(loaded[key])
                abl_df = results_to_dataframe(loaded[key])
                if not abl_df.empty and best_name:
                    best_rows = abl_df[abl_df["name"] == best_name]
                    if not best_rows.empty:
                        best_mean = best_rows.iloc[0]["avg_waiting_time_mean"]
                        if baseline_mean is not None and baseline_mean != 0:
                            improvement = (baseline_mean - best_mean) / abs(baseline_mean) * 100.0
                            direction = "improvement" if improvement > 0 else "degradation"
                            lines.append(
                                f"- **{label}:** best config \"{best_name}\" — "
                                f"{abs(improvement):.1f}% {direction} vs baseline FedRL"
                            )
                        else:
                            lines.append(f"- **{label}:** best config \"{best_name}\" (baseline mean unavailable)")
                    else:
                        lines.append(f"- **{label}:** results available but best config not found")
                else:
                    lines.append(f"- **{label}:** results available but empty")
            else:
                lines.append(f"- **{label}:** results not available")

    else:
        lines.append("- Baseline results not available — run baseline campaign first.")

    lines.append("")

    # ------------------------------------------------------------------
    # 3. Baseline Comparison
    # ------------------------------------------------------------------
    lines += [
        "## Baseline Comparison",
        "",
    ]

    baseline_dir = campaign_dirs.get("baseline", "")
    if baseline_results:
        try:
            generate_all_outputs(baseline_dir, figures_dir)
            lines += [
                "![Baseline avg wait time](chart_avg_waiting_time.png)",
                "",
                "### LaTeX Table (avg_waiting_time)",
                "",
            ]
            table_path = os.path.join(figures_dir, "table_avg_waiting_time.tex")
            if os.path.exists(table_path):
                with open(table_path, encoding="utf-8") as fh:
                    table_content = fh.read()
                lines += [
                    "```latex",
                    table_content.strip(),
                    "```",
                    "",
                ]
        except Exception as exc:
            lines += [f"*Baseline output generation failed: {exc}*", ""]
    else:
        lines += ["*Baseline results not available.*", ""]

    # ------------------------------------------------------------------
    # 4. FedProx Ablation
    # ------------------------------------------------------------------
    lines += [
        "## FedProx Ablation",
        "",
    ]

    fedprox_dir = campaign_dirs.get("fedprox", "")
    fedprox_results = loaded.get("fedprox", [])

    if fedprox_results:
        try:
            tbl_path = os.path.join(figures_dir, "table_fedprox_pvalues.tex")
            generate_ablation_table_with_pvalues(
                fedprox_results, "fedavg_baseline", "avg_waiting_time", tbl_path
            )
            conv_path = os.path.join(figures_dir, "chart_convergence_fedprox.png")
            plot_convergence_curves(fedprox_results, conv_path)
            lines += [
                "### Convergence Curves",
                "",
                "![FedProx convergence](chart_convergence_fedprox.png)",
                "",
                "### Ablation Table with Wilcoxon p-values",
                "",
            ]
            if os.path.exists(tbl_path):
                with open(tbl_path, encoding="utf-8") as fh:
                    lines += ["```latex", fh.read().strip(), "```", ""]
        except Exception as exc:
            lines += [f"*FedProx output generation failed: {exc}*", ""]
    else:
        lines += ["*FedProx ablation results not available.*", ""]

    # ------------------------------------------------------------------
    # 5. Cooperative Ablation
    # ------------------------------------------------------------------
    lines += [
        "## Cooperative Reward Ablation",
        "",
    ]

    coop_results = loaded.get("cooperative", [])

    if coop_results:
        try:
            tbl_path = os.path.join(figures_dir, "table_cooperative_pvalues.tex")
            generate_ablation_table_with_pvalues(
                coop_results, "selfish_baseline", "avg_waiting_time", tbl_path
            )
            conv_path = os.path.join(figures_dir, "chart_convergence_cooperative.png")
            plot_convergence_curves(coop_results, conv_path)
            lines += [
                "### Convergence Curves",
                "",
                "![Cooperative convergence](chart_convergence_cooperative.png)",
                "",
                "### Ablation Table with Wilcoxon p-values",
                "",
            ]
            if os.path.exists(tbl_path):
                with open(tbl_path, encoding="utf-8") as fh:
                    lines += ["```latex", fh.read().strip(), "```", ""]
        except Exception as exc:
            lines += [f"*Cooperative output generation failed: {exc}*", ""]
    else:
        lines += ["*Cooperative reward ablation results not available.*", ""]

    # ------------------------------------------------------------------
    # 6. Time-of-Day Ablation
    # ------------------------------------------------------------------
    lines += [
        "## Time-of-Day Ablation",
        "",
    ]

    tod_results = loaded.get("tod", [])

    if tod_results:
        try:
            tbl_path = os.path.join(figures_dir, "table_tod_pvalues.tex")
            generate_ablation_table_with_pvalues(
                tod_results, "fixed_demand", "avg_waiting_time", tbl_path
            )
            conv_path = os.path.join(figures_dir, "chart_convergence_tod.png")
            plot_convergence_curves(tod_results, conv_path)
            lines += [
                "### Convergence Curves",
                "",
                "![Time-of-Day convergence](chart_convergence_tod.png)",
                "",
                "### Ablation Table with Wilcoxon p-values",
                "",
            ]
            if os.path.exists(tbl_path):
                with open(tbl_path, encoding="utf-8") as fh:
                    lines += ["```latex", fh.read().strip(), "```", ""]
        except Exception as exc:
            lines += [f"*Time-of-Day output generation failed: {exc}*", ""]
    else:
        lines += ["*Time-of-Day ablation results not available.*", ""]

    # ------------------------------------------------------------------
    # 7. Combined Extensions
    # ------------------------------------------------------------------
    lines += [
        "## Combined Extensions",
        "",
    ]

    ablation_map = {}
    for key, label in [("fedprox", "FedProx"), ("cooperative", "Cooperative"), ("tod", "ToD")]:
        if key in loaded and loaded[key]:
            ablation_map[label] = loaded[key]

    if baseline_results and ablation_map:
        try:
            comb_tbl_path = os.path.join(figures_dir, "table_combined_extensions.tex")
            generate_combined_extensions_table(baseline_results, ablation_map, "avg_waiting_time", comb_tbl_path)
            comb_chart_path = os.path.join(figures_dir, "chart_combined_comparison.png")
            plot_combined_comparison(baseline_results, ablation_map, comb_chart_path)
            lines += [
                "![Combined comparison](chart_combined_comparison.png)",
                "",
                "### Combined Extensions Table",
                "",
            ]
            if os.path.exists(comb_tbl_path):
                with open(comb_tbl_path, encoding="utf-8") as fh:
                    lines += ["```latex", fh.read().strip(), "```", ""]
        except Exception as exc:
            lines += [f"*Combined extensions output generation failed: {exc}*", ""]
    else:
        lines += ["*Combined extensions comparison requires baseline and at least one ablation.*", ""]

    # ------------------------------------------------------------------
    # 8. Per-Topology Breakdown
    # ------------------------------------------------------------------
    lines += [
        "## Per-Topology Breakdown",
        "",
    ]

    all_results = []
    for key in ["baseline", "fedprox", "cooperative", "tod"]:
        if key in loaded:
            all_results.extend(loaded[key])

    if all_results:
        for topo in ["grid-3x3", "grid-5x5"]:
            chart_path = os.path.join(figures_dir, f"chart_topology_{topo}.png")
            try:
                plot_per_topology(all_results, topo, "avg_waiting_time", chart_path)
                lines += [
                    f"### {topo}",
                    "",
                    f"![{topo} per-topology](chart_topology_{topo}.png)",
                    "",
                ]
            except Exception as exc:
                lines += [f"*Per-topology chart for {topo} failed: {exc}*", ""]
    else:
        lines += ["*No results available for per-topology breakdown.*", ""]

    # ------------------------------------------------------------------
    # 9. Statistical Tests Summary
    # ------------------------------------------------------------------
    lines += [
        "## Statistical Tests",
        "",
        "| Comparison | Statistic | p-value | Significant |",
        "| --- | --- | --- | --- |",
    ]

    ablation_baselines = {
        "fedprox": "fedavg_baseline",
        "cooperative": "selfish_baseline",
        "tod": "fixed_demand",
    }

    for key, baseline_name in ablation_baselines.items():
        abl_results = loaded.get(key, [])
        if not abl_results:
            continue
        baseline_result = next(
            (r for r in abl_results if r.get("config", {}).get("name") == baseline_name),
            None,
        )
        if baseline_result is None:
            continue
        for r in abl_results:
            name = r.get("config", {}).get("name", "")
            if name == baseline_name:
                continue
            wc = wilcoxon_compare(baseline_result, r, "avg_waiting_time")
            if wc["valid"]:
                lines.append(
                    f"| {baseline_name} vs {name} "
                    f"| {wc['statistic']:.2f} "
                    f"| {wc['p_value']:.4f} "
                    f"| {'Yes' if wc['significant'] else 'No'} |"
                )
            else:
                lines.append(
                    f"| {baseline_name} vs {name} | n/a | n/a | n/a |"
                )

    lines.append("")

    # ------------------------------------------------------------------
    # Write report
    # ------------------------------------------------------------------
    report_content = "\n".join(lines) + "\n"
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report_content)

    logger.info("EXPERIMENT_REPORT.md written to %s", output_path)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Parse CLI arguments and generate EXPERIMENT_REPORT.md."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(
        description="Generate EXPERIMENT_REPORT.md from SEAL campaign results.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--results-dir",
        default="results/campaigns",
        help="Root directory containing campaign subdirectories.",
    )
    parser.add_argument(
        "--output-dir",
        default="results/figures",
        help="Output directory for figures, tables, and the report.",
    )
    args = parser.parse_args()

    # Auto-discover campaign directories
    campaign_dirs = {}
    known_campaigns = {
        "baseline": "baseline",
        "fedprox": "fedprox-ablation",
        "cooperative": "cooperative-ablation",
        "tod": "tod-ablation",
    }
    for key, subdir in known_campaigns.items():
        campaign_dirs[key] = os.path.join(args.results_dir, subdir)

    output_path = os.path.join(args.output_dir, "EXPERIMENT_REPORT.md")

    generate_experiment_report(
        campaign_dirs=campaign_dirs,
        figures_dir=args.output_dir,
        output_path=output_path,
    )

    print(f"Report written to: {output_path}")


if __name__ == "__main__":
    main()
